spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL:validate}
    show-sql: ${SQL_SHOW:true}
    properties:
      hibernate:
        format_sql: ${SQL_FORMAT:true}
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 30s

jwt:
  header: Authorization
  prefix: Bearer
  secret: ${SECRET}
  accessExpiration: 271000
  refreshExpiration: 604800

email:
  template:
    path: src/main/resources/EmailSendTemplate.html

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}